# Generated by Django 5.0.4 on 2024-09-10 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_booking_active_booking_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='travel.discount'),
        ),
    ]
